# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]     = "#070D0B"

# Main text color
theme[main_fg]     = "#C2D0CF"

# Title color for boxes
theme[title]       = "#EBF5F3"

# Highlight color for keyboard shortcuts
theme[hi_fg]       = "#EBF5F3"

# Background color of selected items
theme[selected_bg] = "#46635E"

# Foreground color of selected items
theme[selected_fg] = "#859899"

# Color of inactive/disabled text
theme[inactive_fg] = "#39524D"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]  = "#88D1AA"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]   = "#88D1AA"

# Cpu box outline color
theme[cpu_box]     = "#C28F89"

# Memory/disks box outline color
theme[mem_box]     = "#BD9BD1"

# Net up/down box outline color
theme[net_box]     = "#7BB7D1"

# Processes box outline color
theme[proc_box]    = "#CAD487"

# Box divider line and small boxes line color
theme[div_line]    = "#39524D"

# Temperature graph colors
theme[temp_start] = "#CAD487"
theme[temp_mid]   = ""
theme[temp_end]   = "#C28F89"

# CPU graph colors
theme[cpu_start] = "#88D1AA"
theme[cpu_mid]   = ""
theme[cpu_end]   = "#8A7F42"

# Mem/Disk free meter
theme[free_start] = "#8AD4CE"
theme[free_mid]   = ""
theme[free_end]   = "#CAD487"

# Mem/Disk cached meter
theme[cached_start] = "#859899"
theme[cached_mid]   = ""
theme[cached_end]   = "#46635E"

# Mem/Disk available meter
theme[available_start] = "#39524D"
theme[available_mid]   = ""
theme[available_end]   = "#39524D"

# Mem/Disk used meter
theme[used_start] = "#39524D"
theme[used_mid]   = ""
theme[used_end]   = "#39524D"

# Download graph colors
theme[download_start] = "#39524D"
theme[download_mid]   = "#39524D"
theme[download_end]   = "#39524D"

# Upload graph colors
theme[upload_start] = "#39524D"
theme[upload_mid]   = "#39524D"
theme[upload_end]   = "#39524D"
